"""create_agents_and_runs

Revision ID: e19bc21a3432
Revises: d5ce6d5235e0
Create Date: 2026-09-16 15:29:24.228014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e19bc21a3432'
down_revision: Union[str, None] = 'd5ce6d5235e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active_revision_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_drafts',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('agent_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dependency_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'content_hash', name='uq_agent_revision_content_hash'),
    sa.UniqueConstraint('agent_id', 'revision_number', name='uq_agent_revision_number')
    )
    op.create_index(op.f('ix_agent_revisions_agent_id'), 'agent_revisions', ['agent_id'], unique=False)
    op.create_table('agent_revision_dependencies',
    sa.Column('owner_revision_id', sa.UUID(), nullable=False),
    sa.Column('dependency_kind', sa.String(length=64), nullable=False),
    sa.Column('dependency_revision_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_revision_id'], ['agent_revisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('owner_revision_id', 'dependency_kind', 'dependency_revision_id')
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_revision_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_name', sa.String(length=64), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sanitized_error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_revision_id'], ['agent_revisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_agent_revision_id'), 'runs', ['agent_revision_id'], unique=False)
    op.create_index(op.f('ix_runs_conversation_id'), 'runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_runs_thread_id'), 'runs', ['thread_id'], unique=False)

    op.execute("""
    CREATE OR REPLACE FUNCTION prevent_revision_mutation()
    RETURNS TRIGGER AS $$
    BEGIN
        RAISE EXCEPTION 'agent_revisions is immutable and cannot be updated or deleted';
    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER trg_agent_revisions_immutable
    BEFORE UPDATE OR DELETE ON agent_revisions
    FOR EACH ROW EXECUTE FUNCTION prevent_revision_mutation();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
    DROP TRIGGER IF EXISTS trg_agent_revisions_immutable ON agent_revisions;
    DROP FUNCTION IF EXISTS prevent_revision_mutation();
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_thread_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_conversation_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_agent_revision_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('agent_revision_dependencies')
    op.drop_index(op.f('ix_agent_revisions_agent_id'), table_name='agent_revisions')
    op.drop_table('agent_revisions')
    op.drop_table('agent_drafts')
    op.drop_table('agents')
    # ### end Alembic commands ###
